#!/usr/bin/env python
# regimen_analysis.py - Análisis de regímenes de mercado

print('🔍 ANÁLISIS DE RÉGIMEN DE MERCADO')
print('=' * 50)
print()
print('RÉGIMENES POSIBLES:')
print('  • BULL MARKET    - Mercado alcista')
print('  • BEAR MARKET    - Mercado bajista')
print('  • RANGE MARKET   - Mercado lateral (lo que se detectó)')
print('  • VOLATILE MARKET- Mercado volátil')
print('  • NEUTRAL MARKET - Mercado neutro')
print()
print('CRITERIOS DEL SISTEMA PARA CRYPTO (muy sensibles):')
print()
print('1️⃣ VOLATILE MARKET:')
print('   - volatility_20 > 0.015 (1.5% volatilidad)')
print('   - OR volatility_10 > 0.02 (2% volatilidad corta)')
print('   => Estrategia: HOLD conservadora')
print()
print('2️⃣ BULL TREND:')
print('   - trend_alignment >= 3 (medias ascendendo)')
print('   - AND price_vs_ma10 > 0.005 (0.5% sobre MA10)')
print('   - OR momentum_20 > 0.001 (0.1% momentum 20 períodos)')
print('   => Estrategia: BUY agresiva, PT: 2.5%, SL: 1.2%')
print()
print('3️⃣ BEAR TREND:')
print('   - trend_alignment <= -3 (medias descendiendo)')
print('   - AND price_vs_ma10 < -0.005 (-0.5% bajo MA10)')
print('   - OR momentum_20 < -0.001 (-0.1% momentum)')
print('   => Estrategia: SELL agresiva, PT: 2.5%, SL: 1.2%')
print()
print('4️⃣ RANGE MARKET (DETECTADO AHORA):')
print('   - abs(price_vs_ma10) < 0.008 (0.8% cerca de MA10)')
print('   - AND volatility_20 < 0.025 (2.5% volatilidad)')
print('   => Estrategia: Mean-reversion, PT: 0.8%, SL: 1.5%')
print()
print('5️⃣ NEUTRAL:')
print('   - Cuando ninguna condición se cumple')
print('   => Estrategia: HOLD segura')
print()
print('⚠️ DETECCIONES ULTRA-SENSIBLES PARA CRYPTO:')
print('   - Thresholds momentum: 0.1% vs 0.2% típico')
print('   - Multi-timeframe: MA10, MA20, MA50')
print('   - Periodos analizados: 10-20-50 períodos')
print()
print('🎯 SI "RANGE" NO ES CORRECTO:')
print('   - Ajustar thresholds en regime_classifier.py')
print('   - Validar con datos históricos')
print('   - Verificar lógica de filtros')
print()

print('⏱️ FRECUENCIA DE CAMBIOS DE RÉGIMEN EN CRIPTO:')
print('=' * 50)
print()
print('ENCRIPTOMONEDAS vs MERCADOS TRADICIONALES:')
print()
print('📊 MERCADOS TRADICIONALES:')
print('   - Acciones/S&P500: Cambios cada meses/años')
print('   - Forex/USD: Cambios diarios/semanas')
print('   - Bonos: Cambios meses/años')
print()
print('🚀 ENCRIPTOMONEDAS (MUCHO MÁS RÁPIDO):')
print('   - BITCOIN puede cambiar régimen cada:')
print('     • Horas (durante FOMO/news)')
print('     • Días (eventos normales)')
print('     • Semanas (tendencias mayores)')
print('   - ALTCOINS: Hasta más rápido')
print()
print('⚡ EVENTOS QUE GATILLAN CAMBIOS RÁPIDOS:')
print('   - News/Notificaciones inesperadas')
print('   - Regulaciones políticas')
print('   - Movimientos de whales')
print('   - Cambios en exchanges')
print('   - Ciclos FOMO/FUD diarios')
print()
print('📈 LÓGICA ACTUAL DEL SISTEMA:')
print('   - Clasifica cada ciclo (cada 8 segundos)')
print('   - Confirma cambio con 2/3 últimas detecciones')
print('   - Thresholds ultra-sensibles para cambios rápidos')
print()
print('🕐 FRECUENCIA REAL OBSERVADA:')
print('   - Verifica logs del sistema')
print('   - Monitor cambios en tiempo real')
print('   - BTC: Puede cambiar 3-5 veces/día en mercados volátil')
print('   - ETH: Hasta más frecuente')
print()
print('⚠️ RIESGO: Overfitting por cambios muy frecuentes')
print('   - False signals por noise de corto término')
print('   - Detección oversensitive')
print()
